nginx:
  build: nginx-image
  links:
    - letsencrypt
    - app
  environment:
    - MY_DOMAIN_NAME=awstestdev.doctorinsta.com
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes_from:
    - letsencrypt
letsencrypt:
  image: quay.io/letsencrypt/letsencrypt:latest
  command:  bash -c "sleep 24 && certbot certonly --standalone -d awstestdev.doctorinsta.com --text --agree-tos --email sandeep.mahto@opstree.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  entrypoint: ""
  volumes:
    - /etc/letsencrypt
    - /var/lib/letsencrypt
  ports:
    - "80"
    - "443"
  environment:
    - TERM=xterm
app:
  build: app-image
  environment:
    - DJANGO_SETTINGS_MODULE=sampleApp.settings.prod
  ports:
    - "80"